2021-10-12 23:59:53,147 INFO    MainThread:23024 [wandb_setup.py:_flush():69] setting env: {}
2021-10-12 23:59:53,147 INFO    MainThread:23024 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-12 23:59:53,147 INFO    MainThread:23024 [wandb_init.py:_log_setup():342] Logging user logs to f:\Lab\nfs\base-visob\wandb\run-20211012_235953-3nbu1pq9\logs\debug.log
2021-10-12 23:59:53,147 INFO    MainThread:23024 [wandb_init.py:_log_setup():343] Logging internal logs to f:\Lab\nfs\base-visob\wandb\run-20211012_235953-3nbu1pq9\logs\debug-internal.log
2021-10-12 23:59:53,148 INFO    MainThread:23024 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001F0287B2A90>
2021-10-12 23:59:53,148 INFO    MainThread:23024 [wandb_init.py:init():375] calling init triggers
2021-10-12 23:59:53,148 INFO    MainThread:23024 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-10-12 23:59:53,148 INFO    MainThread:23024 [wandb_init.py:init():424] starting backend
2021-10-12 23:59:53,148 INFO    MainThread:23024 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-10-12 23:59:53,161 INFO    MainThread:23024 [backend.py:ensure_launched():135] starting backend process...
2021-10-12 23:59:53,324 INFO    MainThread:23024 [backend.py:ensure_launched():139] started backend process with pid: 4068
2021-10-12 23:59:53,325 INFO    MainThread:23024 [wandb_init.py:init():429] backend started and connected
2021-10-12 23:59:53,330 INFO    MainThread:23024 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-10-12 23:59:53,331 INFO    MainThread:23024 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-10-12 23:59:53,331 INFO    MainThread:23024 [wandb_init.py:init():477] updated telemetry
2021-10-12 23:59:53,331 INFO    MainThread:23024 [wandb_init.py:init():500] communicating current version
2021-10-12 23:59:55,268 INFO    MainThread:23024 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-12 23:59:55,270 INFO    MainThread:23024 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-12 23:59:55,435 INFO    MainThread:23024 [wandb_init.py:init():540] starting run threads in backend
2021-10-12 23:59:59,216 INFO    MainThread:23024 [wandb_run.py:_console_start():1601] atexit reg
2021-10-12 23:59:59,219 INFO    MainThread:23024 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-10-12 23:59:59,219 INFO    MainThread:23024 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-10-12 23:59:59,221 INFO    MainThread:23024 [wandb_run.py:_redirect():1536] Redirects installed.
2021-10-12 23:59:59,221 INFO    MainThread:23024 [wandb_init.py:init():565] run started, returning control to user process
2021-10-12 23:59:59,575 INFO    MainThread:23024 [wandb_init.py:_pause_backend():256] pausing backend
2021-10-12 23:59:59,575 INFO    MainThread:23024 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-10-13 00:00:13,493 INFO    MainThread:23024 [wandb_init.py:_resume_backend():265] resuming backend
2021-10-13 00:00:13,550 INFO    MainThread:23024 [wandb_init.py:_pause_backend():256] pausing backend
2021-10-13 00:00:13,550 INFO    MainThread:23024 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-10-13 00:00:39,089 INFO    MainThread:23024 [wandb_init.py:_resume_backend():265] resuming backend
2021-10-13 00:00:39,099 INFO    MainThread:23024 [wandb_setup.py:_flush():69] setting env: {}
2021-10-13 00:00:39,099 INFO    MainThread:23024 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-13 00:00:39,099 INFO    MainThread:23024 [wandb_init.py:_log_setup():342] Logging user logs to f:\Lab\nfs\base-visob\wandb\run-20211013_000039-1kqv6emi\logs\debug.log
2021-10-13 00:00:39,099 INFO    MainThread:23024 [wandb_init.py:_log_setup():343] Logging internal logs to f:\Lab\nfs\base-visob\wandb\run-20211013_000039-1kqv6emi\logs\debug-internal.log
2021-10-13 00:00:39,100 INFO    MainThread:23024 [wandb_init.py:init():375] calling init triggers
2021-10-13 00:00:39,100 INFO    MainThread:23024 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-10-13 00:00:39,100 INFO    MainThread:23024 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3nbu1pq9
2021-10-13 00:00:39,102 INFO    MainThread:23024 [wandb_run.py:finish():1271] finishing run sreeraj/UFPR-Ocular/3nbu1pq9
